### ISSUE TITLE
[FEATURE] How to make it work with operator ?

### ISSUE THREAD

**Issue by actalexandre** [opensearch-project/i18n-plugin#31]
How to install this plugin on an Opensearch Dashboards deployed with [the operator](https://github.com/opensearch-project/opensearch-k8s-operator) ?

**Comment by dblock** [comment]
@actalexandre Try the OpenSearch public Slack to ask this?

https://opensearch.org/slack.html

I'll close this for now, reopen if there's a bug with using the plugin with operator.
